### ISSUE TITLE
Cypress App preview is stuck on API calls screen

### ISSUE THREAD

**Issue by vlcekr** [filiphric/cypress-plugin-api#60] opened 2022-11-11 05:38 UTC
Hi Filip,
we use cypress-plugin-api v2.3.3 + Cypress v 11.0.1 and there is issue of Cypress App preview not switching back to tested application after making api calls. 

We have tests for application front-end, it just simulates user behavior but at some point we make api calls to make something happen on the background. After these api calls, test should continue in testing application front-end. Unfortunately, in Cypress App preview, the screen is stuck on API calls view and doesn't go back to tested APP and fails.

Could you please take a look at it? Thanks!

**Comment by lucasdonato** [comment] 2022-11-11 09:56
The same problem happened to me. In my E2E tests, sometimes the screen gets stuck with the request preview

**Comment by filiphric** [comment] 2022-11-11 10:31
Sure, I'll make sure to fix this once I identify the issue. A reproducible example would really help here. If you are able to provide this, that would be great 👍

**Comment by vlcekr** [comment] 2022-11-11 10:55
You can reproduce it easily with this test
`describe('test', () => {
	it('doesnt switch back to app', () => {
		cy.visit('https://www.typescriptlang.org/docs/');
		cy.api('https://api.publicapis.org/entries');
		cy.contains('TS for the New Programmer').click(); // this will fail because there is api screen displayed and it doesn't switch back to website
	});
});`

**Comment by filiphric** [comment] 2022-11-12 09:31
@vlcekr are you using `snapshotOnly` in your test? I can replicate the issue with the code you sent me, but only when `snapshotOnly` is set to `false` (which is default)

**Comment by filiphric** [comment] 2022-11-12 09:32
@lucasdonato does this happen when `snapshotOnly` mode is set to `true`?

**Comment by filiphric** [comment] 2022-12-20 09:49
Hey! I’m still unable to replicate this issue. I found some minor errors that I’m going to fix, but as far as the described issue goes, I’m not able to help. I tried this:
```ts
describe('test', { env: { snapshotOnly: true} }, () => {
	it('doesnt switch back to app', () => {
		cy.visit('https://www.typescriptlang.org/docs/');
		cy.api('https://api.publicapis.org/entries');
		cy.contains('TS for the New Programmer').click();
	});
});
```

when `snapshotOnly` mode is set, all works as intended, UI view hides. when it is not set, it’s `false` by default, so you are not able to select elements on visited page (as expected).

Closing this for now, feel free to reopen

**Closed by filiphric** 2022-12-20 09:49 UTC
Labels: bug, needs investigation
