### ISSUE TITLE
Display the clicked step on the right pane

### ISSUE THREAD

**Issue by muratkeremozcan** [filiphric/cypress-plugin-api#69] opened 2022-11-18 20:02 UTC
When we are running the test, we always have the UI scroll the the latest API call, which is great.

Once the test is over, if we click on a step, it does not get focused on in the UI; we have to scroll all the way to the bottom to see the matching call. 

It would be great if we clicked on the step and saw the relevant UI step without having to scroll.

Repro:

```bash
git clone https://github.com/muratkeremozcan/cypress-crud-api-test.git
cd cypress-crud-api-test
yarn cy:open
```
Run any test (I ran the spok test).
Click on one of the middle steps; we do not get the matching UI on the right pane, we have to scroll to the bottom.

https://user-images.githubusercontent.com/34237651/202792549-14a7e9fd-8fb9-4326-a401-4b22adac37cf.mp4

**Comment by filiphric** [comment] 2022-11-18 23:48
this is a duplicate of #58, but I already have a solution ready, will be releasing it in couple of minutes

**Closed by filiphric** 2022-11-18 23:48 UTC
